# Project Information
sonar.projectKey=calculator-project
sonar.projectName=Calculator Project
sonar.projectVersion=1.0

# SonarQube Server
sonar.host.url=http://192.168.2.80:9000

# Source Code
sonar.sources=src
sonar.tests=tests

# Encoding
sonar.sourceEncoding=UTF-8

# C/C++ Analysis
sonar.cfamily.compile-commands=build/compile_commands.json
