sonar.projectKey=calculator-project

sonar.projectName=Calculator Project

sonar.projectVersion=1.0

sonar.sources=src

sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.cfamily.compile-commands=build/compile_commands.json
sonar.host.url=http://192.168.2.80:9000
sonar.token=sqa_62b663c27042b996d2e1f0db09ba9a46d70a1aaa
